---
- name: Find PHP configuration file
  shell: find /etc -name 'php.ini'
  register: php_config_files
  changed_when: false

- name: Set PHP timezone
  replace: dest={{ item }}
           regexp=';date.timezone =.*'
           replace='date.timezone = {{ rubedo_php_date_timezone }}'
  with_items: php_config_files.stdout_lines
  notify: Restart Apache

- name: Find APC configuration file
  shell: find /etc -name 'apc.ini'
  register: apc_files
  changed_when: false

- name: Set APC shm_size
  lineinfile: dest={{ item }}
              line='apc.shm_size = {{ rubedo_php_apc_shm_size }}'
  with_items: apc_files.stdout_lines
  notify: Restart Apache

