---
- name: Debian | Install packages
  apt: name={{ item }}
       state=present
       update_cache=yes
       cache_valid_time=3600
  with_items: rubedo_web_packages

- name: Debian | Install apache modules
  apache2_module: name={{ item }}
                  state=present
  with_items: rubedo_web_apache.mods
  notify: apache-restart
