---
- include: install-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Get list of PHP modules installed
  shell: php -m
  register: php_modules
  changed_when: false

- name: Install PECL extensions
  shell: printf "\n" | pecl install {{ item }}
  when: php_modules.stdout.find(item) == -1
  with_items: rubedo_pecl.extensions
  ignore_errors: yes

- name: Configure PHP to use PECL extensions
  shell: echo "extension={{ item }}.so" > {{ rubedo_pecl.conf_dir }}/{{ item }}.ini
  when: php_modules.stdout.find(item) == -1
  with_items: rubedo_pecl.extensions
  notify: Restart Apache
