---
# Web role tasks
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - rubedo
    - always

- include: install.yml
  tags:
    - rubedo
    - install

- include: configure.yml
  tags:
    - rubedo
    - configure

- include: download.yml
  tags:
    - rubedo
    - download
  when: rubedo_download|bool

